config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'players#index'

    resources :players
    resources :games
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  VALID_COUNTS = [3, 4].freeze

  has_many :player_games, dependent: :destroy
  has_many :players, through: :player_games
  accepts_nested_attributes_for :player_games

  validates :players_count, presence: true, inclusion: { in: VALID_COUNTS }
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  validates :name, presence: true
  has_many :games, through: :player_games
end

app/models/player_game.rb
# frozen_string_literal: true

class PlayerGame < ApplicationRecord
  belongs_to :player
  belongs_to :game

  has_many :turns, dependent: :destroy
end

app/models/turn.rb
# frozen_string_literal: true

class Turn < ApplicationRecord
  belongs_to :player
  belongs_to :player_game
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

module Web
  class ApplicationController < ApplicationController
  end
end

app/controllers/web/games_controller.rb
# frozen_string_literal: true

module Web
  class GamesController < Web::ApplicationController
    def new
      @game = Game.new
      @game.player_games.build
    end

    def create
      game_params = params[:game]
      players = Player.where(id: game_params[:player_ids])
      @game = Game.create(players_count: game_params[:players_count], players: players)
      if @game.save
        redirect_to @game
      else
        redirect_back(fallback_location: new_game_path)
      end
    end

    def show
      @game = Game.find(params[:id])
    end
  end
end

app/controllers/web/players_controller.rb
# frozen_string_literal: true

module Web
  class PlayersController < Web::ApplicationController
    def index
      @players = Player.all
      render :index
    end

    def new
      @player = Player.new
    end

    def create
      player_params = params[:player]
      @player = Player.create(name: player_params[:name])
      if @player.save
        redirect_to :root
      else
        redirect_to :back
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebJoker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/web/games/new.html.haml
= simple_form_for(@game, action: 'create') do |form|
  = form.input :players_count, collection: [3, 4]
  = form.association :players
  = form.submit

app/views/web/games/show.html.haml
%h1
  Joker game at
  = @game.created_at.strftime('%D')

%h2
  Players
  - @game.players.each do |player|
    %h3
      = player.name

app/views/web/players/index.html.haml
= link_to "Create Player", new_player_url
= link_to "New Game", new_game_url
- @players.each do |player|
  %h1
    = player.name

app/views/web/players/new.html.haml
= simple_form_for(@player, action: 'create') do |form|
  = form.input :name
  = form.submit